@baseUrl = {{$dotenv BASE_URL}}

###
# @name createModuleExample
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/transaction/module-examples HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name createManyModuleExample
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/transaction/module-examples/create-many HTTP/1.1
Accept: application/json
Content-Type: application/json

[
  {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
]

###
# @name retrieveAllModuleExample
GET {{baseUrl}}/v1/transaction/module-examples HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name retrieveModuleExample
# @prompt id
GET {{baseUrl}}/v1/transaction/module-examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name updateModuleExample
# @prompt id
# @prompt name
# @prompt phone
PATCH {{baseUrl}}/v1/transaction/module-examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name updateManyModuleExample
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/transaction/module-examples/update-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "filter": {
    "name": "{{name}}"
  },
  "data": {
    "phone": "{{phone}}"
  }
}

###
# @name deleteModuleExample
# @prompt id
DELETE {{baseUrl}}/v1/transaction/module-examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name deleteManyModuleExample
# @prompt id1
# @prompt id2
POST {{baseUrl}}/v1/transaction/module-examples/delete-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "ids": ["{{id1}}","{{id2}}"]
}

###
# @name createTransactionModuleExample
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/transaction/module-examples/transaction HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "data1": {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  "data2": {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
}